name: mathx
description: "MathX is a null-safe Dart package for easy geometry calculations (area) with double and formatted string outputs."
version: 0.0.1
homepage: https://github.com/mayurpawar17/mathx.git

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: